apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LGROW101/basic-argocd.git
    targetRevision: HEAD
    path: k8s/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: full-assessment-tax
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LGROW101/basic-argocd.git
    targetRevision: HEAD
    path: k8s/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: full-assessment-tax
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LGROW101/basic-argocd.git
    targetRevision: HEAD
    path: k8s/db
  destination:
    server: https://kubernetes.default.svc
    namespace: full-assessment-tax
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
